import turtle
import time
from turtle import *

screen = turtle.Screen()
t = turtle.Turtle()
speed(10)
time.sleep(2)

t.penup()
t.goto(-200, 350)
t.pendown()

t.color("orange")
t.begin_fill()
t.forward(600)
t.right(90)
t.forward(126)
t.right(90)
t.forward(600)
t.end_fill()
t.left(90)
t.forward(126)

t.color("green")
t.begin_fill()
t.forward(126)
t.left(90)
t.forward(600)
t.left(90)
t.forward(126)
t.end_fill()

t.penup()
t.goto(180, 164)
t.pendown()
t.color("navy")
t.begin_fill()
t.circle(50)
t.end_fill()

t.penup()
t.goto(175, 164)
t.pendown()
t.color("white")
t.begin_fill()
t.circle(45)
t.end_fill()

t.penup()
t.goto(90, 159)
t.pendown()
t.color("navy")
for i in range(24):
    t.begin_fill()
    t.circle(3)
    t.end_fill()
    t.penup()
    t.forward(10.75)
    t.right(15)
    t.pendown()

t.penup()
t.goto(137, 164)
t.pendown()
t.begin_fill()
t.circle(10)
t.end_fill()

t.penup()
t.goto(129, 164)
t.pendown()
t.pensize(2)
for i in range(24):
    t.forward(48)
    t.backward(48)
    t.left(15)

t.penup()
t.goto(-200,350)
t.pendown()
t.color("yellow")
t.pensize(15)
t.backward(600)

t.color("brown")
t.left(90)
t.forward(80)
t.left(90)
t.forward(40)
t.left(90)
t.forward(80)
t.penup()
t.backward(80)
t.pendown()
t.backward(80)
t.right(90)
t.forward(40)
t.left(90)
t.forward(320)
t.left(90)
t.forward(40)
t.left(90)
t.forward(160)
t.penup()
t.backward(80)
t.pendown()
t.right(90)
t.forward(40)
t.left(90)
t.forward(80)

t.penup()
t.goto(-250, 150)
t.pendown()
t.color("purple")
t.write("AZADI KA AMRIT MAHOTSAV ", move=True, align="right", font=("Bauhaus 93", 30, "normal"))

t.penup()
t.goto(-600, 100)
t.pendown()
t.color("orange")
t.write("presented by coder_byz", move=False, align="left", font=("Forte", 20, "normal"))

turtle.done()